## CVXPY Basic Knapsack Problem (Binary Integer Programming)

In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [1]:
import cvxpy
import numpy as np

# The data for the Knapsack problem
# P is total weight capacity of sack
# weights and utilities are also specified
P = 165
weights = np.array([23, 31, 29, 44, 53, 38, 63, 85, 89, 82])
utilities = np.array([92, 57, 49, 68, 60, 43, 67, 84, 87, 72])

# The variable we are solving for
selection = cvxpy.Bool(len(weights))

# The sum of the weights should be less than or equal to P
weight_constraint = weights * selection <= P

# Our total utility is the sum of the item utilities
total_utility = utilities * selection

# We tell cvxpy that we want to maximize total utility 
# subject to weight_constraint. All constraints in 
# cvxpy must be passed as a list
knapsack_problem = cvxpy.Problem(cvxpy.Maximize(total_utility), [weight_constraint])

# Solving the problem
knapsack_problem.solve(solver=cvxpy.GLPK_MI)

309.0

In [2]:
print(selection.value)

[[1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]]


## Track Feature Binary Integer Programming

In [2]:
import sys
import os
import json
import matplotlib.pyplot as plt
from pprint import pprint
import numpy as np
from datetime import datetime
import pandas as pd
import seaborn as sns

sys.path.append(os.path.abspath('../'))
from data import Data

In [3]:
d = Data()

In [4]:
tracks = d.getTrackFeatures()

In [5]:
tracks

array([[0.458, 0.591, 5, ..., 184.913, 161187, 3],
       [0.455, 0.623, 8, ..., 182.345, 220293, 4],
       [0.742, 0.753, 1, ..., 132.064, 222727, 4],
       ...,
       [0.488, 0.275, 2, ..., 97.547, 242667, 3],
       [0.624, 0.851, 9, ..., 128.03, 185578, 4],
       [0.553, 0.891, 4, ..., 82.011, 252794, 4]], dtype=object)

In [7]:
tracksFiltered = tracks[:, 0]

In [8]:
tracksFiltered

array([0.458, 0.455, 0.742, ..., 0.488, 0.624, 0.553], dtype=object)

In [9]:
import cvxpy
import numpy as np
from cvxpy import *

trackLength = 10

ideal = 0.4

selection = cvxpy.Bool(len(tracks))

length_max_constraint = sum_entries(selection) <= trackLength
length_min_constraint = sum_entries(selection) >= 3

total_utility = abs(sum_entries((tracksFiltered * selection)) - (ideal * sum_entries(selection)))

knapsack_problem = cvxpy.Problem(cvxpy.Minimize(total_utility), [length_min_constraint, length_max_constraint])

knapsack_problem.solve(solver=cvxpy.GLPK_MI)

0.0

In [10]:
np.sum(selection.value)

3.0

In [11]:
itemindex = np.where(selection.value==[1])

In [12]:
itemindex

(array([1418, 1972, 2082], dtype=int64), array([0, 0, 0], dtype=int64))

In [13]:
tracks[[1418, 1972, 2082]]

array([[0.4, 0.496, 9, -7.793, 1, 0.0328, 0.202, 0, 0.528, 0.136,
        142.017, 324027, 3],
       [0.4, 0.671, 2, -4.193, 1, 0.0295, 0.0708, 0, 0.258, 0.254,
        148.573, 379467, 4],
       [0.4, 0.535, 0, -6.835, 1, 0.0351, 0.577, 0, 0.321, 0.086, 131.8,
        248587, 4]], dtype=object)