## CVXPY Basic Knapsack Problem (Binary Integer Programming)

In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import cvxpy
import numpy as np

# The data for the Knapsack problem
# P is total weight capacity of sack
# weights and utilities are also specified
P = 165
weights = np.array([23, 31, 29, 44, 53, 38, 63, 85, 89, 82])
utilities = np.array([92, 57, 49, 68, 60, 43, 67, 84, 87, 72])

# The variable we are solving for
selection = cvxpy.Bool(len(weights))

# The sum of the weights should be less than or equal to P
weight_constraint = weights * selection <= P

# Our total utility is the sum of the item utilities
total_utility = utilities * selection

# We tell cvxpy that we want to maximize total utility 
# subject to weight_constraint. All constraints in 
# cvxpy must be passed as a list
knapsack_problem = cvxpy.Problem(cvxpy.Maximize(total_utility), [weight_constraint])

# Solving the problem
knapsack_problem.solve(solver=cvxpy.GLPK_MI)

AttributeError: module 'cvxpy' has no attribute 'Bool'

In [ ]:
print(selection.value)

## Track Feature Binary Integer Programming

In [5]:
import sys
import os
import json
import matplotlib.pyplot as plt
from pprint import pprint
import numpy as np
from datetime import datetime
import pandas as pd
import seaborn as sns

sys.path.append(os.path.abspath('../'))
from data import Data

ModuleNotFoundError: No module named 'spotipy'

In [3]:
d = Data()

NameError: name 'Data' is not defined

In [ ]:
tracks = d.getTrackFeatures()

In [6]:
tracks

array([[0.458, 0.591, 5, ..., 184.913, 161187, 3],
       [0.455, 0.623, 8, ..., 182.345, 220293, 4],
       [0.742, 0.753, 1, ..., 132.064, 222727, 4],
       ...,
       [0.488, 0.275, 2, ..., 97.547, 242667, 3],
       [0.624, 0.851, 9, ..., 128.03, 185578, 4],
       [0.553, 0.891, 4, ..., 82.011, 252794, 4]], dtype=object)

In [65]:
tracksFiltered = tracks[:15000, 0:2]

In [66]:
tracksFiltered

array([[0.458, 0.591],
       [0.455, 0.623],
       [0.742, 0.753],
       ...,
       [0.501, 0.981],
       [0.689, 0.963],
       [0.729, 0.656]], dtype=object)

In [67]:
tracksFiltered.shape

(15000, 2)

In [68]:
tracksFiltered[:2,0] * np.array([0,1])

array([0.0, 0.455], dtype=object)

In [69]:
import cvxpy as cp
import numpy as np
from cvxpy import *

trackLength = 15

# ideal constraints
ideal = [0.8, 0.2]
weights = [1, 1]
cp.atoms.elementwise.abs
selection = cp.Variable(len(tracksFiltered), boolean=True)

length_max_constraint = cp.sum(selection) <= trackLength
length_min_constraint = cp.sum(selection) >= trackLength

diff = []
sel = tracksFiltered[:,0] * selection.T

#cost = cp.transforms.scalarize.weighted_sum([cp.sum(cp.atoms.elementwise.abs((tracksFiltered[:,i] * selection.T) - ideal[i])) for i in range(tracksFiltered.shape[1])], weights)

knapsack_problem = cvxpy.Problem(cvxpy.Minimize(cp.sum(abs(sel - ideal[0]))), [length_min_constraint, length_max_constraint])

knapsack_problem.solve(solver=cvxpy.GLPK_MI)

C:\ProgramData\Anaconda3\lib\site-packages\cvxpy\problems\problem.py:613: RuntimeWarning: overflow encountered in long_scalars
  if self.max_big_small_squared < big*small**2:


4.85722573273506e-17

In [70]:
np.sum(selection.value)

15.0

In [71]:
itemindex = np.where(selection.value==[1])

In [72]:
itemindex

(array([ 161,  202, 1072, 1797, 3479, 4115, 5392, 5574, 5921, 6073, 7283,
        8340, 8548, 8777, 9681], dtype=int64),)

In [73]:
tracksFiltered[itemindex]

array([[0.324, 0.308],
       [0, 0.242],
       [0.476, 0.197],
       [0, 0.532],
       [0, 0.16],
       [0, 3.85e-05],
       [0, 0.00274],
       [0, 0.719],
       [0, 0.288],
       [0, 0.192],
       [0, 2.02e-05],
       [0, 0.016],
       [0, 0.23],
       [0, 0.382],
       [0, 0.259]], dtype=object)

In [24]:
tracksFiltered[:10]

array([[0.458, 0.591],
       [0.455, 0.623],
       [0.742, 0.753],
       [0.733, 0.711],
       [0.584, 0.947],
       [0.507, 0.446],
       [0.295, 0.498],
       [0.695, 0.828],
       [0.253, 0.197],
       [0.648, 0.598]], dtype=object)

In [49]:
np.abs(tracksFiltered[:,0]-0.2).min()

0.0